---
- name: checkout kaldur repo
  git: repo=https://github.com/alexclear/kaldur.git dest=/opt/kaldur

- name: install jester
  shell: nimble install -y jester

- name: checkout prometheus client repo
  git: repo=https://github.com/alexclear/prometheus_client_nim.git dest=/root/.nimble/pkgs/prometheus-0.1.0

- name: add kaldur user
  user: name=kaldur state=present

- name: create /var/lib/kaldur
  file: state=directory dest=/var/lib/kaldur owner=kaldur group=kaldur

- name: build kaldur
  shell: cd /opt/kaldur && nim c --threads:on kaldur.nim

- name: install perf
  apt: name="linux-tools-{{ ansible_kernel }}" state=present

- name: clone FlameGraph
  git: repo=https://github.com/brendangregg/FlameGraph.git dest=/opt/FlameGraph

- name: put sudoers file
  template: src=kaldur dest=/etc/sudoers.d/kaldur owner=root group=root mode=0440

- name: put systemd unit file
  template: src=kaldur.service dest=/etc/systemd/system/kaldur.service owner=root group=root mode=0644

- name: enable kaldur service
  service: name=kaldur enabled=yes state=started
